# Generated by Django 5.2 on 2026-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Fijo')], default='porcentaje', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
